language: node_js
node_js:
  - 12.16.1
cache: yarn
before_install:
  - yarn global add serverless
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: deploy
      script: yarn --production
      deploy:
        - provider: script
          script: yarn deploy --stage dev
          skip_cleanup: true
          on:
            branch: develop
        - provider: script
          script: yarn deploy --stage prod
          skip_cleanup: true
          on:
            branch: master
