language: node_js
node_js:
  - 8.10.0
cache: yarn
jobs:
    include:
      - stage: test
        script:
          - yarn lint
          - yarn test
      - stage: deploy
        script: skip
        deploy:
          - provider: script
            script: yarn deploy --stage dev
            on:
              branch: develop
